spring:
    datasource:
        url: jdbc:${DB_URI}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        format-sql: true
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

    servlet:
        multipart:
            max-file-size: 1000MB
            max-request-size: 1000MB

    application:
        name: moments

server:
    port: ${PORT:8080}
    servlet:
        context-path: /api

custom:
    video:
        path: ${VIDEO_PATH:videos/}